{{- range $shootCluster := .Values.shootClusters}}
  {{- if $shootCluster}}
---
apiVersion: gardener.orchestrate.cloud.sap/v1alpha1
kind: AdminKubeconfigRequest
metadata:
  name: {{ required "A valid value is required! (.Values.gardener.controlPlane.shootClusters[].name)" $shootCluster.name | lower | quote}}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  forProvider:
    validFor: 1h0s
    renewAfter: 45m0s
    shootRef:
      name: {{ required "A valid value is required! (.Values.gardener.controlPlane.shootClusters[].name)" $shootCluster.name | quote}}
      namespace: {{ required "A valid value is required! (.Values.gardener.controlPlane.shootClusters[].projectNamespace)" $shootCluster.projectNamespace | quote}}
  providerConfigRef:
    name: {{ required "A valid value is required! (.Values.gardener.controlPlane.shootClusters[].gardenerOrchestrateCloudProviderConfigRefName)" $shootCluster.gardenerOrchestrateCloudProviderConfigRefName | quote}}
  writeConnectionSecretToRef:
    name: gardener-shoot-kubeconfig-{{required "A valid value is required! (.Values.gardener.controlPlane.shootClusters[].name)" $shootCluster.name}}
    namespace: default
  {{- end }}
{{- end }}
