{{- range $shootCluster := .Values.shootClusters}}
  {{- if and ($shootCluster) (ne $shootCluster.name "") }}
---
apiVersion: gardener.orchestrate.cloud.sap/v1alpha1
kind: ViewerKubeconfigRequest
metadata:
  name: {{ required "A valid value is required! (.Values.shootClusters[].name)" $shootCluster.name | lower | quote}}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  forProvider:
    validFor: {{ $shootCluster.viewerKubeconfigValidFor | default "1h0s" }}
    renewAfter: {{ $shootCluster.viewerKubeconfigRenewAfter | default "45m0s" }}
    shootRef:
      name: {{ required "A valid value is required! (.Values.shootClusters[].name)" $shootCluster.name | quote}}
      namespace: {{ required "A valid value is required! (.Values.shootClusters[].projectNamespace)" $shootCluster.projectNamespace | quote}}
  providerConfigRef:
    name: {{ required "A valid value is required! (.Values.shootClusters[].gardenerOrchestrateCloudProviderConfigRefName)" $shootCluster.gardenerOrchestrateCloudProviderConfigRefName | quote}}
  writeConnectionSecretToRef:
    name: gardener-shoot-viewer-kubeconfig-{{required "A valid value is required! (.Values.shootClusters[].name)" $shootCluster.name}}
    namespace: {{ $shootCluster.writeConnectionSecretToRefNamespace | default "default" | quote }}
  {{- end }}
{{- end }}
