{{- range $item := .Values.cloudFoundryEnvironments }}
  {{- if and ($item) (ne $item.name "") }}
---
apiVersion: environment.btp.sap.crossplane.io/v1alpha1
kind: CloudFoundryEnvironment
metadata:
  name: {{required "A valid value is required! (.Values.cloudFoundryEnvironments[].btpSapCrossplaneProviderConfigRefName)" $item.btpSapCrossplaneProviderConfigRefName | lower }}-{{required "A valid value is required! (.Values.cloudFoundryEnvironments[].name)" $item.name | lower }}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  providerConfigRef:
    name: {{required "A valid value is required! (.Values.cloudFoundryEnvironments[].btpSapCrossplaneProviderConfigRefName)" $item.btpSapCrossplaneProviderConfigRefName }}
  forProvider:
    {{- toYaml  $item.forProvider | nindent 4 }}
  cloudManagementRef:
    {{- toYaml  $item.cloudManagementRef | nindent 4 }}    
  subaccountRef:
    {{- toYaml  $item.subaccountRef | nindent 4 }}
    {{- if $item.writeConnectionSecretToRef}}
  writeConnectionSecretToRef:
    {{- $item.writeConnectionSecretToRef | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
