# The Chart.yaml file is required for a chart. See all avaiable fields: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: crossplane-provider-apiextensions
description: A Helm Chart to template crossplane API extensions compositions.
type: application
icon: "https://avatars.githubusercontent.com/u/45158470?s=48&v=4"
version: 0.0.5
appVersion: "1.20.0"
home: "https://github.com/openmcp-project/blueprints"
sources:
  # apiextensions.crossplane.io/v1beta1 EnvironmentConfig
  - https://github.com/crossplane/crossplane
  - https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/EnvironmentConfig/v1beta1
  # apiextensions.crossplane.io/v1beta1 Usage
  - https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Usage/v1alpha1
deprecated: false
