---
########################################################################################################################
###! /!\ this file is only used in github pipeline to template a valid and NOT empty helm manifest! #####
########################################################################################################################
environmentConfigs:
- name: "example-environment"
  data:
    locations:
      us: us-east-2
      eu: eu-north-1
    key1: value1
    key2: value2
    key3:
      - item1
      - item2
########################################################################################################################
usages:
- name: "protect-production-database"
  spec:
    of:
      apiVersion: rds.aws.upbound.io/v1beta1
      kind: Instance
      resourceRef:
        name: my-database
    reason: "Production Database - should never be deleted!"
- name: "release-uses-cluster"
  spec:
    of:
      apiVersion: eks.upbound.io/v1beta1
      kind: Cluster
      resourceRef:
        name: my-cluster
    by:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      resourceRef:
        name: my-prometheus-chart
########################################################################################################################
########################################################################################################################
compositions:
- name: "example-composition"
  spec:
    compositeTypeRef:
      apiVersion: api.example/v1alpha1
      kind: XDatabase
    mode: "Pipeline"
    pipeline:
      - step: compose-resources
        functionRef:
          name: function-patch-and-transform
        input:
          apiVersion: pt.fn.crossplane.io/v1beta1
          kind: Resources
          resources:
            - name: bucket
              base:
                apiVersion: s3.aws.upbound.io/v1beta1
                kind: Bucket
                spec:
                  forProvider:
                    region: us-east-2
########################################################################################################################
compositeResourceDefinitions:
- name: "xdatabases.api.example"
  spec:
    group: api.example
    names:
      kind: XDatabase
      plural: xdatabases
    claimNames:
      kind: Database
      plural: databases
    versions:
      - name: v1alpha1
        served: true
        referenceable: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  region:
                    type: string
                    description: "The region where the database will be created."
########################################################################################################################
