apiVersion: v2
name: crossplane-provider-configs
description: A Helm chart to template crossplane provider config manifests to orchestrate resources.
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# A URL to an SVG or PNG image to be used as an icon
icon: "https://avatars.githubusercontent.com/u/45158470?s=48&v=4"
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.21
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.20.0"
sources:
  # aws.upbound.io/v1beta1 ProviderConfig
  - https://github.com/crossplane-contrib/provider-upjet-aws
  - https://marketplace.upbound.io/providers/upbound/provider-family-aws/v2.7.1/resources/aws.upbound.io/ProviderConfig/v1beta1
  # azure.upbound.io/v1beta1 ProviderConfig
  - https://github.com/crossplane-contrib/provider-upjet-azure
  - https://marketplace.upbound.io/providers/upbound/provider-family-azure/v2.7.1/resources/azure.upbound.io/ProviderConfig/v1beta1
  # btp.sap.crossplane.io/v1alpha1 ProviderConfig
  - https://github.com/SAP/crossplane-provider-btp
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/btp.sap.crossplane.io/ProviderConfig/v1alpha1@v1.13.0
  # cloudfoundry.crossplane.io/v1beta1 ProviderConfig
  - https://github.com/SAP/crossplane-provider-cloudfoundry
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-cloudfoundry/cloudfoundry.crossplane.io/ProviderConfig/v1beta1@v1.0.0
  # gardener.orchestrate.cloud.sap/v1alpha1 ProviderConfig (SAP-internal)
  - https://github.tools.sap/cloud-orchestration/crossplane-provider-gardener-auth
  # gcp.upbound.io/v1beta1 ProviderConfig
  - https://github.com/crossplane-contrib/provider-upjet-gcp
  - https://marketplace.upbound.io/providers/upbound/provider-family-gcp/v3.0.1/resources/gcp.upbound.io/ProviderConfig/v1beta1
  # helm.crossplane.io/v1beta1 ProviderConfig
  - https://github.com/crossplane-contrib/provider-helm
  - https://doc.crds.dev/github.com/crossplane-contrib/provider-helm/helm.crossplane.io/ProviderConfig/v1beta1@v1.2.0
  # kubernetes.crossplane.io/v1alpha1 ProviderConfig
  # kubernetes.m.crossplane.io/v1alpha1 ClusterProviderConfig
  - https://github.com/crossplane-contrib/provider-kubernetes
  - https://doc.crds.dev/github.com/crossplane-contrib/provider-kubernetes/kubernetes.crossplane.io/ProviderConfig/v1alpha1
  - https://doc.crds.dev/github.com/crossplane-contrib/provider-kubernetes/kubernetes.m.crossplane.io/ClusterProviderConfig/v1alpha1
  # vault.upbound.io/v1beta1 ProviderConfig
  - https://github.com/upbound/provider-vault
  - https://doc.crds.dev/github.com/upbound/provider-vault/vault.upbound.io/ProviderConfig/v1beta1
