{{- range $service := .Values.services }}
  {{- if and ($service) (ne $service.name "") }}
---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: {{required "A valid instanceName is required (.Values.services[].instance.name)" $service.instance.name }}
  namespace: {{required "A valid namespace is required (.Values.services[].namespace)" $service.namespace }}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  serviceOfferingName: {{required "A valid serviceOfferingName is required (.Values.services[].instance.serviceOfferingName)" $service.instance.serviceOfferingName }}
  servicePlanName: {{required "A valid servicePlanName is required (.Values.services[].instance.servicePlanName)" $service.instance.servicePlanName }}
  parameters:
    {{- toYaml  $service.instance.parameters | nindent 4 }}
  {{- end}}
{{- end}}
