---
########################################################################################################################
###! /!\ this file is only used in github pipeline to template a valid and NOT empty helm manifest! #####
########################################################################################################################
providers:
  - name: "gcp"
    spec:
      package: crossplane/provider-gcp:alpha
  - name: "azure"
    spec:
      ignoreCrossplaneConstraints: false
      package: crossplane/provider-azure:v0.19.0
      packagePullPolicy: IfNotPresent
      revisionActivationPolicy: Automatic
      revisionHistoryLimit: 0
      skipDependencyResolution: false
  - name: "aws"
    spec:
      package: xpkg.upbound.io/upbound/provider-aws:v0.27.0
  - name: "community-aws"
    spec:
      package: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.40.0
########################################################################################################################
functions:
  - name: "function-patch-and-transform"
    spec:
      package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.1.4
########################################################################################################################
configurations:
  - name: "platform-ref-aws"
    spec:
      package: xpkg.upbound.io/upbound/platform-ref-aws:v0.6.0
########################################################################################################################
deploymentRuntimeConfigs:
  - name: "mount-templates"
    spec:
      deploymentTemplate:
        spec:
          selector: {}
          template:
            spec:
              containers:
                - name: package-runtime
                  volumeMounts:
                    - mountPath: /templates
                      name: templates
                      readOnly: true
              volumes:
                - name: templates
                  configMap:
                    name: templates
########################################################################################################################
imageConfigs:
  - name: "acme-packages"
    spec:
      matchImages:
        - type: Prefix
          prefix: registry1.com/acme-co/
      registry:
        authentication:
          pullSecretRef:
            name: acme-registry-credentials
  - name: "verify-acme-packages"
    spec:
      matchImages:
        - type: Prefix
          prefix: registry1.com/acme-co/configuration-foo
        - type: Prefix
          prefix: registry1.com/acme-co/configuration-bar
      verification:
        provider: Cosign
        cosign:
          authorities:
            - name: verify acme packages
              keyless:
                url: https://fulcio.sigstore.dev
                identities:
                  - issuer: https://token.actions.githubusercontent.com
                    subjectRegExp: https://github.com/acme-co/crossplane-packages/*
              attestations:
                - name: verify attestations
                  predicateType: spdxjson
########################################################################################################################
