{{- range $item := .Values.configurations}}
  {{- if and ($item) (ne $item.name "")}}
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: {{required "A valid value is required! (.Values.configurations[].name)" $item.name | lower }}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  {{- required "A valid value is required! (.Values.configurations[].spec)" $item.spec | toYaml | nindent 2 }}
  {{- end }}
{{- end }}