---
########################################################################################################################
# @default -- {}
defaults: 
  roles:
    deletionPolicy: ""
  users:
    deletionPolicy: ""
  policies:
    deletionPolicy: ""
  userPolicyAttachments:
    deletionPolicy: ""
  rolePolicyAttachments:
    deletionPolicy: ""  
  accessKeys:
    deletionPolicy: ""
  groups:
    deletionPolicy: ""
  groupMemberships:
    deletionPolicy: ""
  groupPolicyAttachments:
    deletionPolicy: ""
  instanceProfiles:
    deletionPolicy: ""
  rolePolicies:
    deletionPolicy: ""
  openIDConnectProviders:
    deletionPolicy: ""
  samlProviders:
    deletionPolicy: ""
  serviceLinkedRoles:
    deletionPolicy: ""
  userGroupMemberships:
    deletionPolicy: ""
  accountPasswordPolicies:
    deletionPolicy: ""
  accountAliases:
    deletionPolicy: ""
  userLoginProfiles:
    deletionPolicy: ""
########################################################################################################################
# -- Official documentation: [AWS IAM Provider](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest) and [Kind: Role](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/Role/v1beta1)
# @default -- {}
roles:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    # @default -- []
    spec:
      # -- DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted.
      deletionPolicy: ""
      forProvider: []
      # -- ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
      providerConfigRef: []
      # -- PublishConnectionDetailsTo specifies the connection secret config.
      publishConnectionDetailsTo: []
      # -- writeConnectionSecretToRef: optional secret reference.
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: User](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/User/v1beta1)
# @default -- {}
users:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: RolePolicyAttachment](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/RolePolicyAttachment/v1beta1)
# @default -- {}
rolePolicyAttachments:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: Policy](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/Policy/v1beta1)
# @default -- {}
policies:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: UserPolicyAttachment](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/UserPolicyAttachment/v1beta1)
# @default -- {}
userPolicyAttachments:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: AccessKey](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/AccessKey/v1beta1)
# @default -- {}
accessKeys:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: Group](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/Group/v1beta1)
# @default -- {}
groups:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: GroupMembership](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/GroupMembership/v1beta1)
# @default -- {}
groupMemberships:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: GroupPolicyAttachment](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/GroupPolicyAttachment/v1beta1)
# @default -- {}
groupPolicyAttachments:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: InstanceProfile](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/InstanceProfile/v1beta1)
# @default -- {}
instanceProfiles:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: RolePolicy](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/RolePolicy/v1beta1)
# @default -- {}
rolePolicies:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: OpenIDConnectProvider](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/OpenIDConnectProvider/v1beta1)
# @default -- {}
openIDConnectProviders:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: SAMLProvider](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/SAMLProvider/v1beta1)
# @default -- {}
samlProviders:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: ServiceLinkedRole](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/ServiceLinkedRole/v1beta1)
# @default -- {}
serviceLinkedRoles:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: UserGroupMembership](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/UserGroupMembership/v1beta1)
# @default -- {}
userGroupMemberships:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: AccountPasswordPolicy](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/AccountPasswordPolicy/v1beta1)
# @default -- {}
accountPasswordPolicies:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: AccountAlias](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/AccountAlias/v1beta1)
# @default -- {}
accountAliases:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
# -- Official documentation: [Kind: UserLoginProfile](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/latest/resources/iam.aws.upbound.io/UserLoginProfile/v1beta1)
# @default -- {}
userLoginProfiles:
  - name: ""
    labels: []
    annotations: []
    ownerReferences: []
    spec:
      deletionPolicy: ""
      forProvider: []
      providerConfigRef: []
      publishConnectionDetailsTo: []
      writeConnectionSecretToRef: []
########################################################################################################################
