{{- range $item := .Values.credentialsBindings }}
  {{- if and ($item) (ne $item.name "") }}
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: {{required "A valid value is required! (.Values.credentialsBindings[].name)" $item.name | lower | quote}}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  providerConfigRef:
    name: {{required "A valid value is required! (.Values.credentialsBindings[].kubernetesCrossplaneProviderConfigRefName)" $item.kubernetesCrossplaneProviderConfigRefName | quote}}
  forProvider:
    manifest:
      # https://gardener.cloud/docs/gardener/api-reference/security/#security.gardener.cloud/v1alpha1.CredentialsBinding
      apiVersion: security.gardener.cloud/v1alpha1
      kind: CredentialsBinding
      metadata:
        name: {{required "A valid credentials binding name is required! (.Values.credentialsBindings[].credentialsBindingName)" $item.credentialsBindingName | quote}}
        namespace: {{required "A valid Gardener Project Namespace is required! (.Values.credentialsBindings[].projectNamespace)" $item.projectNamespace | quote}}
        {{- if $item.labels}}
        labels:
          {{- $item.labels | toYaml | nindent 10 }}
        {{- end }}
      provider:
        type: {{required "A valid provider type is required! (.Values.credentialsBindings[].cloudProfile)" $item.cloudProfile | quote}}
      credentialsRef:
        {{- required "A valid value is required! (.Values.credentialsBindings[].credentialsRef)" $item.credentialsRef | toYaml | nindent 8 }}
      {{- if $item.quotas }}
      quotas:
        {{- $item.quotas | toYaml | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
