---
#########################################################################################################
# -- accounts contains information and configuration about a specifig [BTP Global Account](https://help.sap.com/docs/btp/sap-business-technology-platform/getting-global-account). :exclamation::exclamation: Managing BTP Global Accounts is [NOT possible](https://pages.github.tools.sap/cloud-orchestration/docs/sap-services/btp-services/account-managment/accounts#use-existing-global-account) at the moment :exclamation::exclamation:
# @default -- {}
accounts:
  # btp.accounts[0].id -- id contains technical identifier of a [BTP Global Account](https://help.sap.com/docs/btp/sap-business-technology-platform/getting-global-account).
  # @default -- {}
  # -- btpSapCrossplaneProviderConfigRefName defines crossplane provider configuration reference name (identifier) of a [BTP Global Account](https://help.sap.com/docs/btp/sap-business-technology-platform/getting-global-account)!
  - btpSapCrossplaneProviderConfigRefName: ""
    # -------------------------------------------------------------------------------------------------------------------------#
    # -- subAccounts contains information and configuration about [BTP Sub-Accounts](https://help.sap.com/docs/btp/sap-business-technology-platform/account-model#loio8d6e3a0fa4ab43e4a421d3ed08128afa).
    # @default -- {}
    subAccounts:
      # btp.accounts[0].subAccounts[0].name -- defines k8s `metadata.name` value of `kind: Subaccount`
      - name: ""
        # -- *optional* adding custom k8s metadata to manifests
        # @default -- []
        metadata:
          # -- *optional* adding custom k8s [annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/)
          # @default -- []
          annotations:
            CloudManagement:
              "crossplane.io/external-name": "..."
            ServiceManager:
              "crossplane.io/external-name": "..."
        # -- SubaccountParameters are the configurable fields of a Subaccount. [CRD Browser](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/subaccount/v1alpha1?path=spec-forProvider)
        # @default -- []
        forProvider:
          # -- defines the display name of the [BTP Sub-Accounts](https://help.sap.com/docs/btp/sap-business-technology-platform/account-model#loio8d6e3a0fa4ab43e4a421d3ed08128afa).
          displayName: ""
          # -- description defines the description of the [BTP Sub-Account](https://help.sap.com/docs/btp/sap-business-technology-platform/account-model#loio8d6e3a0fa4ab43e4a421d3ed08128afa).
          description: ""
          # -- enable beta services and applications?
          betaEnabled:
          # -- [region](https://help.sap.com/docs/btp/sap-business-technology-platform/regions) contains the assigned region of this [BTP Sub-Account](https://help.sap.com/docs/btp/sap-business-technology-platform/account-model#loio8d6e3a0fa4ab43e4a421d3ed08128afa). Each region represents a geographical location (for example, Europe, US East) where applications, data, or services are hosted. Value without "cf-" prefix! e.g. "eu10-canary"
          region: "eu01"
          # --  This value must be unique across all BTP subaccounts
          subdomain: "dev-eu01"
          # -- Available options: NOT_USED_FOR_PRODUCTION, USED_FOR_PRODUCTION, UNSET
          usedForProduction: "NOT_USED_FOR_PRODUCTION"
          # -- subaccountAdmins defines a list of Users (identified via Email Adress) with Admin Permission to this [BTP Sub-Account](https://help.sap.com/docs/btp/sap-business-technology-platform/account-model#loio8d6e3a0fa4ab43e4a421d3ed08128afa). Learn more about [BTP User and Member Management](https://help.sap.com/docs/btp/sap-business-technology-platform/user-and-member-management?locale=en-US).
          subaccountAdmins:
            - your.name@sap.com
        # -- Define Subscriptions for this [BTP Sub-Account](https://help.sap.com/docs/btp/sap-business-technology-platform/account-model#loio8d6e3a0fa4ab43e4a421d3ed08128afa) to subscribe to [BTP Services](https://help.sap.com/docs/btp/sap-business-technology-platform/solutions-and-services?locale=en-US&q=Subscription#services).
        # @default -- {}
        subscriptions:
          # accounts[0].subAccounts[0].subscriptions[0].name -- Name of the Subscription resource - [CRD Browser](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/subscription/v1alpha1).
          - name: ""
            # -- AppName of the app to subscribe to
            appName: ""
            # -- PlanName to subscribe to 
            planName: ""
            # -- *optional* - When a Crossplane Provider creates a managed resource it may generate resource-specific details, like usernames, passwords or connection details like an IP address.
            #   Crossplane stores these details in a Kubernetes Secret object specified by the `writeConnectionSecretToRef` values. Learn more about Crossplane concept [Managed Resources Fields](https://docs.crossplane.io/latest/concepts/managed-resources/#writeconnectionsecrettoref)!
            # @default -- []
            writeConnectionSecretToRef:
              name: ""
              namespace: "ns1"
        # -- contains special [BTP Services](https://help.sap.com/docs/btp/sap-business-technology-platform/solutions-and-services?locale=en-US&q=Subscription#services) (e.g. BTP Service Manager) for this [BTP Sub-Account](https://help.sap.com/docs/btp/sap-business-technology-platform/account-model#loio8d6e3a0fa4ab43e4a421d3ed08128afa).
        # @default -- []
        services:
          # -- Enable/Disable (true/false) BTP Service Manager Subscription.
          #    Please make sure the P/I/D users, used in the Secrets referenced in the `ProviderConfig` are part of your Subaccount's `subaccountAdmins``.
          #    Note: updating subaccountAdmins on an existing Subaccount is not yet supported by the provider. We are aware of this issue (see [feature request](https://github.tools.sap/cloud-orchestration/crossplane-provider-btp-account/issues/284)).
          serviceManager: false
          # -- Enable/Disable (true/false) BTP Cloud Management Service.
          cloudManagement: false
        # -- entitlements defines [BTP Entitlements](https://help.sap.com/docs/btp/sap-business-technology-platform/entitlements-and-quotas) for this [BTP Sub-Account](https://help.sap.com/docs/btp/sap-business-technology-platform/account-model#loio8d6e3a0fa4ab43e4a421d3ed08128afa). 
        # Learn more about managing BTP Entitlement with crossplane [here](https://pages.github.tools.sap/cloud-orchestration/docs/sap-services/btp-services/account-managment/entitlements).
        # @default -- {}
        entitlements:
          # btp.accounts[0].subAccounts[0].entitlements[0].name -- Name of the Entitlement resource - [CRD Browser](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp-account/account.btp.sap.crossplane.io/entitlement/v1alpha1).
          # @default -- -
          - name: ""            
            # serviceName defines the service name of [BTP Entitlements](https://help.sap.com/docs/btp/sap-business-technology-platform/entitlements-and-quotas).
            serviceName: ""
            # -- servicePlanName defines Service Plan Name of this [BTP Entitlements](https://help.sap.com/docs/btp/sap-business-technology-platform/entitlements-and-quotas).
            servicePlanName: ""
            # --  Setting a amount/quota is not supported by multitenant applications and by services that do not permit a numeric quota assignment.
            permitNumericQuota: false
            # -- Used when permitNumericQuota=true. Only set amount for multitenant applications and services that do not permit a numeric quota assignment!
            amount: 0
########################################################################################################################
# -- `directoryEntitlements[].` orchestrate [`kind: DirectoryEntitlement`](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/directoryentitlement/v1alpha1) of [BTP Accounts](https://pages.github.tools.sap/cloud-orchestration/docs/category/account-management).
# @default -- object
directoryEntitlements:
  # -- btpSapCrossplaneProviderConfigRefName defines crossplane provider configuration reference name (identifier) of a [BTP Global Account](https://help.sap.com/docs/btp/sap-business-technology-platform/getting-global-account)!
  - btpSapCrossplaneProviderConfigRefName: ""
    # directoryEntitlements[0].name -- Name of the DirectoryEntitlement resource - [CRD Browser](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/directoryentitlement/v1alpha1?path=metadata).
    # @default -- -
    name: ""
    # -- [forProvider](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/directoryentitlement/v1alpha1) CRD
    forProvider: []
    # -- *optional* - When a Crossplane Provider creates a managed resource it may generate resource-specific details, like usernames, passwords or connection details like an IP address.
    #   Crossplane stores these details in a Kubernetes Secret object specified by the `writeConnectionSecretToRef` values. Learn more about Crossplane concept [Managed Resources Fields](https://docs.crossplane.io/latest/concepts/managed-resources/#writeconnectionsecrettoref)!
    writeConnectionSecretToRef: []
#########################################################################################################
# -- `directories[].` orchestrate [`kind: Directory`](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/directory) of [BTP Accounts](https://pages.github.tools.sap/cloud-orchestration/docs/category/account-management).
# @default -- object
directories:
  # -- btpSapCrossplaneProviderConfigRefName defines crossplane provider configuration reference name (identifier) of a [BTP Global Account](https://help.sap.com/docs/btp/sap-business-technology-platform/getting-global-account)!
  - btpSapCrossplaneProviderConfigRefName: ""
    # directories[0].name -- Name of the Directory resource - [CRD Browser](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/directory).
    # @default -- -
    name: ""
    # -- [forProvider](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/directory) CRD
    forProvider: []
    # -- *optional* - When a Crossplane Provider creates a managed resource it may generate resource-specific details, like usernames, passwords or connection details like an IP address.
    #   Crossplane stores these details in a Kubernetes Secret object specified by the `writeConnectionSecretToRef` values. Learn more about Crossplane concept [Managed Resources Fields](https://docs.crossplane.io/latest/concepts/managed-resources/#writeconnectionsecrettoref)!
    writeConnectionSecretToRef: []
#########################################################################################################
# -- `subaccountServiceBrokers[].` orchestrate [`kind: SubaccountServiceBroker`](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/subaccountservicebroker/) of [BTP Accounts](https://pages.github.tools.sap/cloud-orchestration/docs/category/account-management).
# @default -- object
subaccountServiceBrokers:
  # -- btpSapCrossplaneProviderConfigRefName defines crossplane provider configuration reference name (identifier) of a [BTP Global Account](https://help.sap.com/docs/btp/sap-business-technology-platform/getting-global-account)!
  - btpSapCrossplaneProviderConfigRefName: ""
    # subaccountServiceBrokers[0].name -- Name of the SubaccountServiceBroker resource - [CRD Browser](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/subaccountservicebroker/).
    # @default -- -
    name: ""
    # -- [forProvider](https://pages.github.tools.sap/cloud-orchestration/browser/Providers/provider-btp/account.btp.sap.crossplane.io/subaccountservicebroker/) CRD
    forProvider: []
    # -- *optional* - When a Crossplane Provider creates a managed resource it may generate resource-specific details, like usernames, passwords or connection details like an IP address.
    #   Crossplane stores these details in a Kubernetes Secret object specified by the `writeConnectionSecretToRef` values. Learn more about Crossplane concept [Managed Resources Fields](https://docs.crossplane.io/latest/concepts/managed-resources/#writeconnectionsecrettoref)!
    writeConnectionSecretToRef: []
#########################################################################################################
