{{- range $item := .Values.subnets}}
  {{- if and ($item) (ne $item.name "") }}
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: {{required "A valid value is required! (.Values.subnets[].name)" $item.name | lower }}  
  {{- if $item.annotations}}
  annotations:
    {{- $item.annotations | toYaml | nindent 4 }}
  {{- end }}
  {{- if $item.labels}}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
    {{- $item.labels | toYaml | nindent 4 }}
  {{- end }}
  {{- if $item.ownerReferences}}
  ownerReferences:
    {{- $item.ownerReferences | toYaml | nindent 4 }}  
  {{- end }}
spec:
  deletionPolicy: {{ $item.spec.deletionPolicy | default $.Values.defaults.subnets.deletionPolicy| quote }}  
  forProvider:
    {{- required "A valid value is required! (.Values.subnets[].spec.forProvider)" $item.spec.forProvider | toYaml | nindent 4 }}
  providerConfigRef:
    {{- required "A valid value is required! (.Values.subnets[].spec.providerConfigRef)" $item.spec.providerConfigRef | toYaml | nindent 4 }}    
  {{- if $item.spec.writeConnectionSecretToRef}}
  writeConnectionSecretToRef:
    {{- $item.spec.writeConnectionSecretToRef | toYaml | nindent 4 }}
  {{- end }}
  {{- if $item.spec.writeConnectionSecretToRef}}
  publishConnectionDetailsTo:
    {{- $item.spec.publishConnectionDetailsTo | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}