{{- range $item := .Values.usages}}
  {{- if and ($item) (ne $item.name "") }}
---
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Usage
metadata:
  name: {{required "A valid value is required! (.Values.usages[].name)" $item.name | lower }}
  {{- if $item.annotations}}
  annotations:
    {{- $item.annotations | toYaml | nindent 4 }}
  {{- end }}
  {{- if $item.labels}}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
    {{- $item.labels | toYaml | nindent 4 }}
  {{- end }}
  {{- if $item.ownerReferences}}
  ownerReferences:
    {{- $item.ownerReferences | toYaml | nindent 4 }}  
  {{- end }}
spec:
  {{- required "A valid value is required! (.Values.usages[].spec)" $item.spec | toYaml | nindent 2 }}
  {{- end }}
{{- end }}