---
apiVersion: v2
name: crossplane-provider-btp-security
description: A Helm Chart to template crossplane manifests to manage BTP resources such as Directory, TrustConfiguration and RoleCollection Assignment on BTP.
type: application
icon: "https://avatars.githubusercontent.com/u/45158470?s=48&v=4"
version: 0.0.16
appVersion: "1.1.2"
home: "https://github.com/openmcp-project/blueprints"
sources:
  - https://github.com/SAP/crossplane-provider-btp
  # security.btp.sap.crossplane.io/v1alpha1 GlobalaccountTrustConfiguration
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/security.btp.sap.crossplane.io/GlobalaccountTrustConfiguration/v1alpha1@v1.13.0
  # security.btp.sap.crossplane.io/v1alpha1 RoleCollectionAssignment
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/security.btp.sap.crossplane.io/RoleCollectionAssignment/v1alpha1@v1.13.0
  # security.btp.sap.crossplane.io/v1alpha1 SubaccountApiCredential
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/security.btp.sap.crossplane.io/SubaccountApiCredential/v1alpha1@v1.13.0
  # security.btp.sap.crossplane.io/v1alpha1 SubaccountTrustConfiguration
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/security.btp.sap.crossplane.io/SubaccountTrustConfiguration/v1alpha1@v1.13.0
deprecated: false
