{{- range $item := .Values.serviceCredentialsBindings }}
  {{- if and ($item) (ne $item.name "") }}
---
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceCredentialBinding
metadata:
  name: {{required "A valid value is required! (.Values.serviceKeys[].name)" $item.name | lower }}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  providerConfigRef:
    name: {{required "A valid value is required! (.Values.serviceKeys[].cloudfoundryBtpOrchestrateCloudProviderConfigRefName)" $item.cloudfoundryBtpOrchestrateCloudProviderConfigRefName }}
  forProvider:
    {{- required "A valid value is required! (.Values.spaces[].forProvider)" $item.forProvider | toYaml | nindent 4 }}
    {{- if $item.writeConnectionSecretToRef}}
  writeConnectionSecretToRef:
    {{- $item.writeConnectionSecretToRef | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
