{{- range $item := .Values.helmReleases}}
  {{- if and ($item) (ne $item.name "")}}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{required "A valid value is required! (.Values.helmReleases[].name)" $item.name | lower | quote}}
  namespace: {{ $item.namespace | default $.Values.defaults.namespace | lower | quote }}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  {{- toYaml $item.spec | nindent 2 }}
  {{- end }}
{{- end }}