---
apiVersion: v2
name: crossplane-provider-sap-btp-account
description: A Helm chart to template crossplane manifests to manage SAP BTP resources.
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# A URL to an SVG or PNG image to be used as an icon
icon: "https://avatars.githubusercontent.com/u/45158470?s=48&v=4"
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.14
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.1.2"
home: "https://github.com/SAP/crossplane-provider-btp"
# A list of URLs to source code for this project (optional)
sources:
  - https://github.com/SAP/crossplane-provider-btp
  # account.btp.sap.crossplane.io/v1alpha1 - CloudManagement
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/account.btp.sap.crossplane.io/CloudManagement/v1alpha1@v1.1.2
  # account.btp.sap.crossplane.io/v1alpha1 - Directory
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/account.btp.sap.crossplane.io/Directory/v1alpha1@v1.1.2
  # account.btp.sap.crossplane.io/v1alpha1 - DirectoryEntitlement
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/account.btp.sap.crossplane.io/DirectoryEntitlement/v1alpha1@v1.1.2
  # account.btp.sap.crossplane.io/v1alpha1 - Entitlement
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/account.btp.sap.crossplane.io/Entitlement/v1alpha1@v1.1.2
  # account.btp.sap.crossplane.io/v1alpha1 - ServiceBinding
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/account.btp.sap.crossplane.io/ServiceBinding/v1alpha1@v1.1.2
  # account.btp.sap.crossplane.io/v1alpha1 - ServiceInstance
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/account.btp.sap.crossplane.io/ServiceInstance/v1alpha1@v1.1.2
  # account.btp.sap.crossplane.io/v1beta1 - ServiceManager
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/account.btp.sap.crossplane.io/ServiceManager/v1beta1@v1.1.2
  # account.btp.sap.crossplane.io/v1alpha1 - Subaccount
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/account.btp.sap.crossplane.io/Subaccount/v1alpha1@v1.1.2
  # account.btp.sap.crossplane.io/v1alpha1 - SubaccountServiceBroker
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/account.btp.sap.crossplane.io/SubaccountServiceBroker/v1alpha1@v1.1.2
  # account.btp.sap.crossplane.io/v1alpha1 - Subscription
  - https://doc.crds.dev/github.com/SAP/crossplane-provider-btp/account.btp.sap.crossplane.io/Subscription/v1alpha1@v1.1.2
