{{- range $item := .Values.clusterExternalSecret}}
  {{- if and ($item) (ne $item.name "")}}
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{required "A valid value is required! (.Values.clusterSecretStores[].clusterExternalSecret[].name)" $item.name | lower | quote}}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  {{- if $item.externalSecretName}}
  externalSecretName: {{ $item.externalSecretName | quote }}
  {{- end }}
  {{- if $item.namespaceSelectors}}  
  namespaceSelectors:
    {{- $item.namespaceSelectors | toYaml | nindent 4 }}
  {{- end }}
  refreshTime: {{required "A valid value is required! (.Values.clusterSecretStores[].clusterExternalSecret[].refreshTime)" $item.refreshTime | quote}}
  externalSecretSpec:
    {{- required "A valid value is required! (.Values.clusterSecretStores[].clusterExternalSecret[].externalSecretSpec)" $item.externalSecretSpec | toYaml | nindent 4 }}    
  {{- end }}
{{- end }}