{{- range $item := .Values.clusterSecretStores}}
  {{- if and ($item) (ne $item.name "")}}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{required "A valid value is required! (.Values.clusterSecretStores[].name)" $item.name | lower | quote}}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  {{- if $item.controller}}
  controller: {{ $item.controller | quote }}
  {{- end }}
  provider:
    {{- required "A valid value is required! (.Values.clusterSecretStores[].provider)" $item.provider | toYaml | nindent 4 }}
  {{- end }}
{{- end }}