{{- range $item := .Values.clusterGenerators}}
  {{- if and ($item) (ne $item.name "")}}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: {{required "A valid value is required! (.Values.clusterGenerators[].name)" $item.name | lower | quote}}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  {{- required "A valid value is required! (.Values.clusterGenerators[].spec)" $item.spec | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
