{{- range $externalSecret := .Values.externalSecret}}
  {{- if and ($externalSecret) (ne $externalSecret.name "")}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{required "A valid value is required! (.Values.secretStore[].externalSecret[].name)" $externalSecret.name | lower | quote}}
  namespace: {{ $externalSecret.namespace | default $.Values.defaults.namespace | lower | quote }}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  refreshInterval: {{required "A valid value is required! (.Values.secretStore[].externalSecret[].refreshInterval)" $externalSecret.refreshInterval | quote}}
  secretStoreRef:
    name: {{required "A valid value is required! (.Values.secretStore.name)" $externalSecret.secretStore.name | quote}}    
    kind: {{ default $.Values.defaults.externalSecret.secretStoreRef.kind $externalSecret.secretStore.kind | quote }}
  target:
    name: {{required "A valid value is required! (.Values.secretStore[].externalSecret[].targetSecretName)" $externalSecret.targetSecretName | quote}}
    {{- if $externalSecret.template }}
    template: 
      {{- $externalSecret.template | toYaml | nindent 6 }}
    {{- end }}
    {{- if $externalSecret.creationPolicy }}
    creationPolicy: {{ $externalSecret.creationPolicy | quote }}
    {{- end }}
    {{- if $externalSecret.deletionPolicy }}
    deletionPolicy: {{ $externalSecret.deletionPolicy | quote }}
    {{- end }}
    {{- if $externalSecret.immutable }}
    immutable: {{ $externalSecret.immutable }}
    {{- end }}
  data:
    {{- required "A valid value is required! (.Values.secretStore[].externalSecret[].data)" $externalSecret.data | toYaml | nindent 4 }}    
  {{- end }}
{{- end }}