{{- range $item := .Values.githubAccessTokens}}
  {{- if and ($item) (ne $item.name "")}}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: {{required "A valid value is required! (.Values.githubAccessTokens[].name)" $item.name | lower | quote}}
  namespace: {{ $item.namespace | default $.Values.defaults.namespace | lower | quote }}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  {{- required "A valid value is required! (.Values.githubAccessTokens[].spec)" $item.spec | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
