{{- range $item := .Values.secretStores}}
  {{- if and ($item) (ne $item.name "")}}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{required "A valid value is required! (.Values.secretStore[].name)" $item.name | lower | quote}}
  namespace: {{ $item.namespace | default $.Values.defaults.namespace | lower | quote }}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  provider:
    {{- required "A valid value is required! (.Values.secretStore[].provider)" $item.provider | toYaml | nindent 4 }}
  {{- end }}
{{- end }}