{{- range $account := .Values.accounts}}
  {{- range $item := $account.subAccounts}}
    {{- if and ($item) (ne $item.name "") }}
      {{- if hasKey $item "services" }}
        {{- if hasKey $item.services "serviceManager" }}
          {{- if $item.services.serviceManager}}
---
apiVersion: account.btp.sap.crossplane.io/v1beta1
kind: ServiceManager
metadata:
  name: {{required "A valid value is required! (.Values.accounts[].subAccounts[].name)" $item.name | lower }}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
  {{- template "ServiceManager.annotations" $item }}
spec:
  {{- if and $item.services.serviceManagerConfiguration $item.services.serviceManagerConfiguration.writeConnectionSecretToRef }}
  writeConnectionSecretToRef: {{- $item.services.serviceManagerConfiguration.writeConnectionSecretToRef | toYaml | nindent 4 }}
  {{- else }}
  writeConnectionSecretToRef:
    name: btp-service-manager-{{ required "A valid value is required! (.Values.accounts[].btpSapCrossplaneProviderConfigRefName)" $account.btpSapCrossplaneProviderConfigRefName }}-{{ required "A valid value is required! (.Values.accounts[].subAccounts[].name)" $item.name | lower }}
    namespace: default
  {{- end }}
  forProvider:
    subaccountRef:
      name: {{required "A valid value is required! (.Values.accounts[].subAccounts[].name)" $item.name | lower }}
  providerConfigRef:
    name: {{ required "A valid value is required! (.Values.accounts[].btpSapCrossplaneProviderConfigRefName)" $account.btpSapCrossplaneProviderConfigRefName | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
