---
########################################################################################################################
###! /!\ this file is only used in github pipeline to template a valid and NOT empty helm manifest! #####
########################################################################################################################
shootClusters:
  - name: "name"
    projectNamespace: "projectNamespace"
    gardenerOrchestrateCloudProviderConfigRefName: "gardenerOrchestrateCloudProviderConfigRefName"
    writeConnectionSecretToRefNamespace: "default"
    viewerKubeconfigValidFor: "1h0s"
    viewerKubeconfigRenewAfter: "45m0s"
