---
#########################################################################################################
# -- shootClusters contains information and configuration of Gardener shoot clusters via [kind: AdminKubeconfigRequest](https://gardener.cloud/docs/gardener/api-reference/authentication/).
# @default -- -
shootClusters:
  # gardener.controlPlane.shootClusters[0].name -- name defines technical gardener shoot cluster. Max length 15 and must only be lowercase letters, numbers and hyphens!
  - name: ""
    # -- gardener project namespace. Starts with "garden..." e.g. "garden-aas-dt"
    projectNamespace: "ns1"
    # -- gardenerOrchestrateCloudProviderConfigRefName needs to match crossplane provider configuration reference name (identifier) of SAP garden cluster control plane! (.gardener.controlPlane.shootClusters[*].gardenerOrchestrateCloudProviderConfigRefName)
    gardenerOrchestrateCloudProviderConfigRefName: ""
    # -- writeConnectionSecretToRefNamespace is the namespace where the kubeconfig secret will be written. Default: default.
    writeConnectionSecretToRefNamespace: "default"
    # -- viewerKubeconfigValidFor sets the validity duration for viewer kubeconfigs. Default: 1h0s.
    viewerKubeconfigValidFor: "1h0s"
    # -- viewerKubeconfigRenewAfter sets when viewer kubeconfigs should be renewed. Default: 45m0s.
    viewerKubeconfigRenewAfter: "45m0s"
#########################################################################################################
