---
########################################################################################################################
###! /!\ this file is only used in github pipeline to template a valid and NOT empty helm manifest! #####
########################################################################################################################
instances:
  - name: "rds-instance"
    labels: {}
    annotations: {}
    ownerReferences: {}      
    spec:
      forProvider:
        allocatedStorage: 20
        autoGeneratePassword: true
        autoMinorVersionUpgrade: true
        backupRetentionPeriod: 14
        backupWindow: 09:46-10:16
        dbName: devusdb
        engine: postgres
        engineVersion: "16.1"
        instanceClass: db.t3.micro
        maintenanceWindow: Mon:00:00-Mon:03:00
        passwordSecretRef:
          key: password
          name: dev-us-rds-admin-pw
          namespace: dev-us
        publiclyAccessible: false
        region: us-east-1
        skipFinalSnapshot: true
        storageEncrypted: true
        storageType: gp2
        username: adminuser
      providerConfigRef:
        name: dev-us-aws
      writeConnectionSecretToRef:
        name: dev-us-rds-connection-details
        namespace: dev-us
########################################################################################################################
