{{- range $item := .Values.credentials}}
  {{- if and ($item) (ne $item.name "")}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{required "A valid value is required! (.Values.credentials[].name)" $item.name | lower | quote}}
  namespace:  {{ $item.namespace | default $.Values.defaults.namespace | lower | quote }}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
    {{- if $item.stringData}}
stringData:
      {{- range $key, $value := $item.stringData }}
  {{ $key }}: {{ $value | quote }}  
      {{- end }}
    {{- end }}
    {{- if $item.data}}
data:
  {{- toYaml $item.data | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}