name: PR Status Checks

on:
  pull_request:
    branches:
      - main
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  packages: read
  actions: write
  checks: write
  statuses: write

jobs:  
  pr-status-check:
    if: ${{ github.event.pull_request.head.repo.full_name == 'openmcp-project/blueprint-building-blocks' }}        
    uses: "openmcp-project/blueprint-workflows/.github/workflows/git-pr-status-checks.yml@main"
