{{- range $item := .Values.secretBindings}} 
  {{- if and ($item) (ne $item.name "")}}
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: {{required "A valid value is required! (.Values.secretBindings[].name)" $item.name | lower | quote}}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  providerConfigRef:
    name: {{required "A valid value is required! (.Values.secretBindings[].kubernetesCrossplaneProviderConfigRefName)" $item.kubernetesCrossplaneProviderConfigRefName | quote}} # Set to Kubernetes ProviderConfig
  forProvider:
    manifest:
      # https://gardener.cloud/docs/gardener/api-reference/core/#core.gardener.cloud/v1beta1.SecretBinding
      apiVersion: core.gardener.cloud/v1beta1
      kind: SecretBinding
      metadata:
        labels:
          cloudprofile.garden.sapcloud.io/name: {{required "A valid Cloud Profile is required! (.Values.secretBindings[].cloudProfile)" $item.cloudProfile}}
        {{- if $item.labels}}
          {{- $item.labels | toYaml | nindent 10 }}
        {{- end }}
        name: {{required "A valid Secret Binding Name is required! (.Values.secretBindings[].secretBindingName)" $item.secretBindingName}}
        namespace: {{required "A valid Gardener Project Namespace is required! (.Values.secretBindings[].projectNamespace)" $item.projectNamespace}}    
      provider:
        type: {{required "A valid Cloud Profile is required! (.Values.secretBindings[].cloudProfile)" $item.cloudProfile}}
      {{- if $item.quotas}}
      quotas:     
        {{- $item.quotas | toYaml | nindent 8 }}
      {{- end }}
      secretRef:
        {{- required "A valid value is required! (.Values.secretBindings[].secretRef)" $item.secretRef | toYaml | nindent 8 }}
  {{- end }}
{{- end }}
